baseURL = "https://datagronomist.netlify.app/"
title = "Datagronomist"
theme = "PaperMod"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
publishDir = "docs"

[params]
  description = "Science, agriculture, and society"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2



